all: 
	gcc solution.c test1.c -lm -o LS1
	gcc solution.c test2.c -lm -o LS2
	gcc solution.c test3.c -lm -o LS3

gr:
	chmod +x printError2.gpi
	./printError2.gpi
	chmod +x printError3.gpi
	./printError3.gpi